"""empty message

Revision ID: 453ddd4c8c6d
Revises: 
Create Date: 2023-10-26 18:57:51.797170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453ddd4c8c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abbreviation', sa.String(length=3), nullable=False),
    sa.Column('year_founded', sa.Integer(), nullable=False),
    sa.Column('has_previous_name', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id_home', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('fgm_home', sa.Double(), nullable=True),
    sa.Column('fga_home', sa.Double(), nullable=True),
    sa.Column('fg_pct_home', sa.Double(), nullable=True),
    sa.Column('fg3m_home', sa.Double(), nullable=True),
    sa.Column('fg3a_home', sa.Double(), nullable=True),
    sa.Column('fg3_pct_home', sa.Double(), nullable=True),
    sa.Column('ftm_home', sa.Double(), nullable=True),
    sa.Column('fta_home', sa.Double(), nullable=True),
    sa.Column('ft_pct_home', sa.Double(), nullable=True),
    sa.Column('oreb_home', sa.Double(), nullable=True),
    sa.Column('dreb_home', sa.Double(), nullable=True),
    sa.Column('reb_home', sa.Double(), nullable=True),
    sa.Column('ast_home', sa.Double(), nullable=True),
    sa.Column('stl_home', sa.Double(), nullable=True),
    sa.Column('blk_home', sa.Double(), nullable=True),
    sa.Column('tov_home', sa.Double(), nullable=True),
    sa.Column('pf_home', sa.Double(), nullable=True),
    sa.Column('pts_home', sa.Double(), nullable=True),
    sa.Column('team_id_away', sa.Integer(), nullable=True),
    sa.Column('fgm_away', sa.Double(), nullable=True),
    sa.Column('fga_away', sa.Double(), nullable=True),
    sa.Column('fg_pct_away', sa.Double(), nullable=True),
    sa.Column('fg3m_away', sa.Double(), nullable=True),
    sa.Column('fg3a_away', sa.Double(), nullable=True),
    sa.Column('fg3_pct_away', sa.Double(), nullable=True),
    sa.Column('ftm_away', sa.Double(), nullable=True),
    sa.Column('fta_away', sa.Double(), nullable=True),
    sa.Column('ft_pct_away', sa.Double(), nullable=True),
    sa.Column('oreb_away', sa.Double(), nullable=True),
    sa.Column('dreb_away', sa.Double(), nullable=True),
    sa.Column('reb_away', sa.Double(), nullable=True),
    sa.Column('ast_away', sa.Double(), nullable=True),
    sa.Column('stl_away', sa.Double(), nullable=True),
    sa.Column('blk_away', sa.Double(), nullable=True),
    sa.Column('tov_away', sa.Double(), nullable=True),
    sa.Column('pf_away', sa.Double(), nullable=True),
    sa.Column('pts_away', sa.Double(), nullable=True),
    sa.Column('home_win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('jersey', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('from_year', sa.Integer(), nullable=True),
    sa.Column('to_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('teams')
    op.drop_table('seasons')
    # ### end Alembic commands ###
