"""empty message

Revision ID: 4e939f55fd43
Revises: dcc186a9914b
Create Date: 2023-11-17 16:08:38.567581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e939f55fd43'
down_revision = 'dcc186a9914b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_column('season_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_number', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
