"""empty message

Revision ID: d42f36e8c2ad
Revises: 4e939f55fd43
Create Date: 2023-11-17 16:11:42.966164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42f36e8c2ad'
down_revision = '4e939f55fd43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('games_season_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_foreign_key('games_season_id_fkey', 'seasons', ['season_id'], ['id'])

    op.create_table('seasons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='seasons_pkey')
    )
    # ### end Alembic commands ###
