from db import db

class GameModel(db.Model):
    __tablename__ = "games"

    id = db.Column(db.Integer, primary_key=True)
    team_id_home = db.Column(db.Integer)
    season_id = db.Column(db.Integer)
    date = db.Column(db.Date)
    fgm_home = db.Column(db.Double)
    fga_home = db.Column(db.Double)
    fg_pct_home = db.Column(db.Double)
    fg3m_home = db.Column(db.Double)
    fg3a_home = db.Column(db.Double)
    fg3_pct_home = db.Column(db.Double)
    ftm_home = db.Column(db.Double)
    fta_home = db.Column(db.Double)
    ft_pct_home = db.Column(db.Double)
    oreb_home = db.Column(db.Double)
    dreb_home = db.Column(db.Double)
    reb_home = db.Column(db.Double)
    ast_home = db.Column(db.Double)
    stl_home = db.Column(db.Double)
    blk_home = db.Column(db.Double)
    tov_home = db.Column(db.Double)
    pf_home = db.Column(db.Double)
    pts_home = db.Column(db.Double)
    team_id_away = db.Column(db.Integer)
    fgm_away = db.Column(db.Double)
    fga_away = db.Column(db.Double)
    fg_pct_away = db.Column(db.Double)
    fg3m_away = db.Column(db.Double)
    fg3a_away = db.Column(db.Double)
    fg3_pct_away = db.Column(db.Double)
    ftm_away = db.Column(db.Double)
    fta_away = db.Column(db.Double)
    ft_pct_away = db.Column(db.Double)
    oreb_away = db.Column(db.Double)
    dreb_away = db.Column(db.Double)
    reb_away = db.Column(db.Double)
    ast_away = db.Column(db.Double)
    stl_away = db.Column(db.Double)
    blk_away = db.Column(db.Double)
    tov_away = db.Column(db.Double)
    pf_away = db.Column(db.Double)
    pts_away = db.Column(db.Double)
    home_win = db.Column(db.Boolean)